### ISSUE TITLE
非url格式的huatuo-26m数据集请求

### ISSUE THREAD

**Issue by zhuhm1996** [FreedomIntelligence/Huatuo-26M#2]
最新的Github上面[huatuo_consultation_qa](https://huggingface.co/datasets/FreedomIntelligence/huatuo_consultation_qa)数据集是使用url形式的数据，请问您能提供处理好的huatuo-26m数据集吗？包含26,000,000 问题-回答对。

**Comment by zhuhm1996** [comment]
我已经联系了[changmiaowang@cuhk.edu.cn](mailto:changmiaowang@cuhk.edu.cn)和2751245496@qq.com，可是给我的回复是：让我在github上面问。
这就陷入循环了。

**Comment by zhuhm1996** [comment]
请问能直接给个非url格式的数据集的下载连接吗？

**Comment by wabyking** [comment]
感谢你的邮件，我们没有发布非URL的lisence，这有法律风险。后面我们会准备一个协议，签署后我们会给你提供非URL格式的数据集，但是需要遵循只能用作研究目的。

**Comment by zhuhm1996** [comment]
能发一下模板，现在就签吗？我急着用。谢谢！

从 Windows 版邮件发送

发件人: waby
发送时间: 2023年7月13日 9:16
收件人: FreedomIntelligence/Huatuo-26M
抄送: zhuhm1996; Author
主题: Re: [FreedomIntelligence/Huatuo-26M] 非url格式的huatuo-26m数据集请求 (Issue #2)

感谢你的邮件，我们没有发布非URL的lisence，这有法律风险。后面我们会准备一个协议，签署后我们会给你提供非URL格式的数据集，但是需要遵循只能用作研究目的。
