### ISSUE TITLE
FreedomIntelligence/huatuo_encyclopedia_qa 数据来源

### ISSUE THREAD

**Issue by yclzju** [FreedomIntelligence/Huatuo-26M#4]
你好，非常感谢你们开源的数据，huatuo_encyclopedia_qa包括wiki和爬取的问答数据，能有字段区分这两个来源吗？我们想分别分析这两部分的数据质量

**Comment by wangxidong06** [comment]
抱歉没有加上数据源标签，我们考虑近日更新加入标签的数据，加入后会和您联系，感谢您的关注。
